version: '3.9'
services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3001:3000"
    networks:
      - spring-boot-postgres-network
    volumes:
      - ./frontend/:/react-docker:delegated
      - /node_modules
  backend:
    platform: linux/amd64
    build: ./backend
    networks:
      - spring-boot-postgres-network
    env_file: .env
    depends_on:
      - db
    ports:
      - ${APPLICATION_PORT_ON_DOCKER_HOST}:${APPLICATION_PORT_ON_CONTAINER}
    volumes:
      - ./backend/:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT_ON_CONTAINER}"
  websocket-service:
    env_file: .env
    platform: linux/amd64
    build: ./websocket-service
    ports:
      - "8081:8081"
    volumes:
      - ./websocket-service/:/app:delegated
    networks:
      - spring-boot-postgres-network
  db:
    container_name: postgres-container
    image: postgres:14.1-alpine
    env_file: .env
    ports:
      - ${DB_PORT_ON_DOCKER_HOST}:${DB_PORT_ON_CONTAINER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres-network
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - spring-boot-postgres-network
    volumes:
      - redis-data:/data

volumes:
  db:
  redis-data:

networks:
  spring-boot-postgres-network:
    name: spring-boot-postgres-network
    driver: bridge
