FROM golang:latest

ENV GO111MODULE=on \
    CGO_ENABLED=0

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build -o main ." --command=./main
